---
# tasks file for prod
- name: install packages
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - default-jdk
    - tomcat9

- name: deploy app
  copy:
    src: "{{ war_folder }}/hello-1.0.war"
    dest: "{{ tomcat_folder }}"
  notify:
    - restart tomcat